dt:
  print_time:                         True
  print_objects_info:                 False
  record_time:                        True
  record_objects_info:                True
  
  use_lidar:                          True
  use_radar:                          True
  
  sub_image_topic:                    /usb_cam/image_rect_color
  sub_lidar_topic:                    /lidar_points_processed
  sub_radar_topic:                    /mmw_marker
  pub_marker_topic:                   /objects
  pub_obstacle_topic:                 /obstacles
  
  frame_id:                           /laser_link
  align_to_lidar:                     True
  
  calibration_image_file:             calibration_image.yaml
  calibration_lidar_file:             calibration_lidar.yaml
  calibration_radar_file:             calibration_radar.yaml
  
  display_image_raw:                  False
  display_image_segmented:            False
  display_lidar_projected:            False
  
  display_2d_modeling:                False
  display_gate:                       False
  
  display_3d_modeling:                False
  display_frame:                      False
  display_obj_state:                  False
  
  processing_mode: DT # D - detection, DT - detection and tracking
  
  blind_update_limit:                 0
  frame_rate:                         10
  max_id:                             10000
